### ISSUE TITLE
Unexpected behaviour for some cases

### ISSUE THREAD

**Issue by vitalk** [AnthonyDem/LeverX_tasks#2]
https://github.com/AnthonyDem/LeverX_tasks/blob/e9838ec97571da0d1210303730a82bbb0406531d/task2/task2.py#L38

Please ensure the program works as expected when version has less then 3 parts, e.g. 

```
Version('1.0') == Version('1.0.0')
True
```

**Comment by AnthonyDem** [comment]
In this case, is there any chance that after version 1.0, the remainder will go for example -alpha, or is the remainder written only after versions from three positions?

**Comment by vitalk** [comment]
Yes, remainder may prepend short version as well, e.g. "1.0-alpha"

**Comment by AnthonyDem** [comment]
I have done the task. I added a new assertion, but if you try to pass all of them, they will fall somehow, because for example 1.0.1-alpha is not equal to 1.0.1-aplha.1, the checks will be executed correctly if you alternate them, if you remove the last assert and the test for him, also in the opposite direction, if I understood it correctly.
